name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main  # or specify another branch if needed

permissions:
  contents: write
  pages: write

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_book_theme sphinx_design rst2pdf

      - name: Build HTML documentation
        run: |
          sphinx-build -b html source build/html

      - name: Build PDF Documentation
        run: |
          sphinx-build -b pdf source build/pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
